INSERT INTO elite_country (country_id, country_iso, country_name, country_nicename, country_iso3, country_numcode,
                           country_phonecode)
VALUES (nextval('elite_country_seq'), 'AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', '4', '93'),
       (nextval('elite_country_seq'), 'AL', 'ALBANIA', 'Albania', 'ALB', '8', '355'),
       (nextval('elite_country_seq'), 'DZ', 'ALGERIA', 'Algeria', 'DZA', '12', '213'),
       (nextval('elite_country_seq'), 'AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', '16', '1684'),
       (nextval('elite_country_seq'), 'AD', 'ANDORRA', 'Andorra', 'AND', '20', '376'),
       (nextval('elite_country_seq'), 'AO', 'ANGOLA', 'Angola', 'AGO', '24', '244'),
       (nextval('elite_country_seq'), 'AI', 'ANGUILLA', 'Anguilla', 'AIA', '660', '1264'),
       (nextval('elite_country_seq'), 'AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, '0'),
       (nextval('elite_country_seq'), 'AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', '28', '1268'),
       (nextval('elite_country_seq'), 'AR', 'ARGENTINA', 'Argentina', 'ARG', '32', '54'),
       (nextval('elite_country_seq'), 'AM', 'ARMENIA', 'Armenia', 'ARM', '51', '374'),
       (nextval('elite_country_seq'), 'AW', 'ARUBA', 'Aruba', 'ABW', '533', '297'),
       (nextval('elite_country_seq'), 'AU', 'AUSTRALIA', 'Australia', 'AUS', '36', '61'),
       (nextval('elite_country_seq'), 'AT', 'AUSTRIA', 'Austria', 'AUT', '40', '43'),
       (nextval('elite_country_seq'), 'AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', '31', '994'),
       (nextval('elite_country_seq'), 'BS', 'BAHAMAS', 'Bahamas', 'BHS', '44', '1242'),
       (nextval('elite_country_seq'), 'BH', 'BAHRAIN', 'Bahrain', 'BHR', '48', '973'),
       (nextval('elite_country_seq'), 'BD', 'BANGLADESH', 'Bangladesh', 'BGD', '50', '880'),
       (nextval('elite_country_seq'), 'BB', 'BARBADOS', 'Barbados', 'BRB', '52', '1246'),
       (nextval('elite_country_seq'), 'BY', 'BELARUS', 'Belarus', 'BLR', '112', '375'),
       (nextval('elite_country_seq'), 'BE', 'BELGIUM', 'Belgium', 'BEL', '56', '32'),
       (nextval('elite_country_seq'), 'BZ', 'BELIZE', 'Belize', 'BLZ', '84', '501'),
       (nextval('elite_country_seq'), 'BJ', 'BENIN', 'Benin', 'BEN', '204', '229'),
       (nextval('elite_country_seq'), 'BM', 'BERMUDA', 'Bermuda', 'BMU', '60', '1441'),
       (nextval('elite_country_seq'), 'BT', 'BHUTAN', 'Bhutan', 'BTN', '64', '975'),
       (nextval('elite_country_seq'), 'BO', 'BOLIVIA', 'Bolivia', 'BOL', '68', '591'),
       (nextval('elite_country_seq'), 'BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', '70', '387'),
       (nextval('elite_country_seq'), 'BW', 'BOTSWANA', 'Botswana', 'BWA', '72', '267'),
       (nextval('elite_country_seq'), 'BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, '0'),
       (nextval('elite_country_seq'), 'BR', 'BRAZIL', 'Brazil', 'BRA', '76', '55'),
       (nextval('elite_country_seq'), 'IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL,
        NULL, '246'),
       (nextval('elite_country_seq'), 'BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', '96', '673'),
       (nextval('elite_country_seq'), 'BG', 'BULGARIA', 'Bulgaria', 'BGR', '100', '359'),
       (nextval('elite_country_seq'), 'BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', '854', '226'),
       (nextval('elite_country_seq'), 'BI', 'BURUNDI', 'Burundi', 'BDI', '108', '257'),
       (nextval('elite_country_seq'), 'KH', 'CAMBODIA', 'Cambodia', 'KHM', '116', '855'),
       (nextval('elite_country_seq'), 'CM', 'CAMEROON', 'Cameroon', 'CMR', '120', '237'),
       (nextval('elite_country_seq'), 'CA', 'CANADA', 'Canada', 'CAN', '124', '1'),
       (nextval('elite_country_seq'), 'CV', 'CAPE VERDE', 'Cape Verde', 'CPV', '132', '238'),
       (nextval('elite_country_seq'), 'KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', '136', '1345'),
       (nextval('elite_country_seq'), 'CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', '140',
        '236'),
       (nextval('elite_country_seq'), 'TD', 'CHAD', 'Chad', 'TCD', '148', '235'),
       (nextval('elite_country_seq'), 'CL', 'CHILE', 'Chile', 'CHL', '152', '56'),
       (nextval('elite_country_seq'), 'CN', 'CHINA', 'China', 'CHN', '156', '86'),
       (nextval('elite_country_seq'), 'CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, '61'),
       (nextval('elite_country_seq'), 'CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, '672'),
       (nextval('elite_country_seq'), 'CO', 'COLOMBIA', 'Colombia', 'COL', '170', '57'),
       (nextval('elite_country_seq'), 'KM', 'COMOROS', 'Comoros', 'COM', '174', '269'),
       (nextval('elite_country_seq'), 'CG', 'CONGO', 'Congo', 'COG', '178', '242'),
       (nextval('elite_country_seq'), 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
        'Congo, the Democratic Republic of the', 'COD', '180', '242'),
       (nextval('elite_country_seq'), 'CK', 'COOK ISLANDS', 'Cook Islands', 'COK', '184', '682'),
       (nextval('elite_country_seq'), 'CR', 'COSTA RICA', 'Costa Rica', 'CRI', '188', '506'),
       (nextval('elite_country_seq'), 'CI', 'COTE DIVOIRE', 'Cote DIvoire', 'CIV', '384', '225'),
       (nextval('elite_country_seq'), 'HR', 'CROATIA', 'Croatia', 'HRV', '191', '385'),
       (nextval('elite_country_seq'), 'CU', 'CUBA', 'Cuba', 'CUB', '192', '53'),
       (nextval('elite_country_seq'), 'CY', 'CYPRUS', 'Cyprus', 'CYP', '196', '357'),
       (nextval('elite_country_seq'), 'CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', '203', '420'),
       (nextval('elite_country_seq'), 'DK', 'DENMARK', 'Denmark', 'DNK', '208', '45'),
       (nextval('elite_country_seq'), 'DJ', 'DJIBOUTI', 'Djibouti', 'DJI', '262', '253'),
       (nextval('elite_country_seq'), 'DM', 'DOMINICA', 'Dominica', 'DMA', '212', '1767'),
       (nextval('elite_country_seq'), 'DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', '214', '1809'),
       (nextval('elite_country_seq'), 'EC', 'ECUADOR', 'Ecuador', 'ECU', '218', '593'),
       (nextval('elite_country_seq'), 'EG', 'EGYPT', 'Egypt', 'EGY', '818', '20'),
       (nextval('elite_country_seq'), 'SV', 'EL SALVADOR', 'El Salvador', 'SLV', '222', '503'),
       (nextval('elite_country_seq'), 'GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', '226', '240'),
       (nextval('elite_country_seq'), 'ER', 'ERITREA', 'Eritrea', 'ERI', '232', '291'),
       (nextval('elite_country_seq'), 'EE', 'ESTONIA', 'Estonia', 'EST', '233', '372'),
       (nextval('elite_country_seq'), 'ET', 'ETHIOPIA', 'Ethiopia', 'ETH', '231', '251'),
       (nextval('elite_country_seq'), 'FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK',
        '238', '500'),
       (nextval('elite_country_seq'), 'FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', '234', '298'),
       (nextval('elite_country_seq'), 'FJ', 'FIJI', 'Fiji', 'FJI', '242', '679'),
       (nextval('elite_country_seq'), 'FI', 'FINLAND', 'Finland', 'FIN', '246', '358'),
       (nextval('elite_country_seq'), 'FR', 'FRANCE', 'France', 'FRA', '250', '33'),
       (nextval('elite_country_seq'), 'GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', '254', '594'),
       (nextval('elite_country_seq'), 'PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', '258', '689'),
       (nextval('elite_country_seq'), 'TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL,
        '0'),
       (nextval('elite_country_seq'), 'GA', 'GABON', 'Gabon', 'GAB', '266', '241'),
       (nextval('elite_country_seq'), 'GM', 'GAMBIA', 'Gambia', 'GMB', '270', '220'),
       (nextval('elite_country_seq'), 'GE', 'GEORGIA', 'Georgia', 'GEO', '268', '995'),
       (nextval('elite_country_seq'), 'DE', 'GERMANY', 'Germany', 'DEU', '276', '49'),
       (nextval('elite_country_seq'), 'GH', 'GHANA', 'Ghana', 'GHA', '288', '233'),
       (nextval('elite_country_seq'), 'GI', 'GIBRALTAR', 'Gibraltar', 'GIB', '292', '350'),
       (nextval('elite_country_seq'), 'GR', 'GREECE', 'Greece', 'GRC', '300', '30'),
       (nextval('elite_country_seq'), 'GL', 'GREENLAND', 'Greenland', 'GRL', '304', '299'),
       (nextval('elite_country_seq'), 'GD', 'GRENADA', 'Grenada', 'GRD', '308', '1473'),
       (nextval('elite_country_seq'), 'GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', '312', '590'),
       (nextval('elite_country_seq'), 'GU', 'GUAM', 'Guam', 'GUM', '316', '1671'),
       (nextval('elite_country_seq'), 'GT', 'GUATEMALA', 'Guatemala', 'GTM', '320', '502'),
       (nextval('elite_country_seq'), 'GN', 'GUINEA', 'Guinea', 'GIN', '324', '224'),
       (nextval('elite_country_seq'), 'GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', '624', '245'),
       (nextval('elite_country_seq'), 'GY', 'GUYANA', 'Guyana', 'GUY', '328', '592'),
       (nextval('elite_country_seq'), 'HT', 'HAITI', 'Haiti', 'HTI', '332', '509'),
       (nextval('elite_country_seq'), 'HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands',
        NULL, NULL, '0'),
       (nextval('elite_country_seq'), 'VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT',
        '336', '39'),
       (nextval('elite_country_seq'), 'HN', 'HONDURAS', 'Honduras', 'HND', '340', '504'),
       (nextval('elite_country_seq'), 'HK', 'HONG KONG', 'Hong Kong', 'HKG', '344', '852'),
       (nextval('elite_country_seq'), 'HU', 'HUNGARY', 'Hungary', 'HUN', '348', '36'),
       (nextval('elite_country_seq'), 'IS', 'ICELAND', 'Iceland', 'ISL', '352', '354'),
       (nextval('elite_country_seq'), 'IN', 'INDIA', 'India', 'IND', '356', '91'),
       (nextval('elite_country_seq'), 'ID', 'INDONESIA', 'Indonesia', 'IDN', '360', '62'),
       (nextval('elite_country_seq'), 'IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', '364',
        '98'),
       (nextval('elite_country_seq'), 'IQ', 'IRAQ', 'Iraq', 'IRQ', '368', '964'),
       (nextval('elite_country_seq'), 'IE', 'IRELAND', 'Ireland', 'IRL', '372', '353'),
       (nextval('elite_country_seq'), 'IL', 'ISRAEL', 'Israel', 'ISR', '376', '972'),
       (nextval('elite_country_seq'), 'IT', 'ITALY', 'Italy', 'ITA', '380', '39'),
       (nextval('elite_country_seq'), 'JM', 'JAMAICA', 'Jamaica', 'JAM', '388', '1876'),
       (nextval('elite_country_seq'), 'JP', 'JAPAN', 'Japan', 'JPN', '392', '81'),
       (nextval('elite_country_seq'), 'JO', 'JORDAN', 'Jordan', 'JOR', '400', '962'),
       (nextval('elite_country_seq'), 'KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', '398', '7'),
       (nextval('elite_country_seq'), 'KE', 'KENYA', 'Kenya', 'KEN', '404', '254'),
       (nextval('elite_country_seq'), 'KI', 'KIRIBATI', 'Kiribati', 'KIR', '296', '686'),
       (nextval('elite_country_seq'), 'KP', 'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', 'Korea,
        Democratic Peoples Republic of', 'PRK', '408', '850'),
       (nextval('elite_country_seq'), 'KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', '410', '82'),
       (nextval('elite_country_seq'), 'KW', 'KUWAIT', 'Kuwait', 'KWT', '414', '965'),
       (nextval('elite_country_seq'), 'KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', '417', '996'),
       (nextval('elite_country_seq'), 'LA', 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'Lao Peoples Democratic Republic',
        'LAO', '418', '856'),
       (nextval('elite_country_seq'), 'LV', 'LATVIA', 'Latvia', 'LVA', '428', '371'),
       (nextval('elite_country_seq'), 'LB', 'LEBANON', 'Lebanon', 'LBN', '422', '961'),
       (nextval('elite_country_seq'), 'LS', 'LESOTHO', 'Lesotho', 'LSO', '426', '266'),
       (nextval('elite_country_seq'), 'LR', 'LIBERIA', 'Liberia', 'LBR', '430', '231'),
       (nextval('elite_country_seq'), 'LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', '434', '218'),
       (nextval('elite_country_seq'), 'LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', '438', '423'),
       (nextval('elite_country_seq'), 'LT', 'LITHUANIA', 'Lithuania', 'LTU', '440', '370'),
       (nextval('elite_country_seq'), 'LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', '442', '352'),
       (nextval('elite_country_seq'), 'MO', 'MACAO', 'Macao', 'MAC', '446', '853'),
       (nextval('elite_country_seq'), 'MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
        'Macedonia, the Former Yugoslav Republic of', 'MKD', '807', '389'),
       (nextval('elite_country_seq'), 'MG', 'MADAGASCAR', 'Madagascar', 'MDG', '450', '261'),
       (nextval('elite_country_seq'), 'MW', 'MALAWI', 'Malawi', 'MWI', '454', '265'),
       (nextval('elite_country_seq'), 'MY', 'MALAYSIA', 'Malaysia', 'MYS', '458', '60'),
       (nextval('elite_country_seq'), 'MV', 'MALDIVES', 'Maldives', 'MDV', '462', '960'),
       (nextval('elite_country_seq'), 'ML', 'MALI', 'Mali', 'MLI', '466', '223'),
       (nextval('elite_country_seq'), 'MT', 'MALTA', 'Malta', 'MLT', '470', '356'),
       (nextval('elite_country_seq'), 'MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', '584', '692'),
       (nextval('elite_country_seq'), 'MQ', 'MARTINIQUE', 'Martinique', 'MTQ', '474', '596'),
       (nextval('elite_country_seq'), 'MR', 'MAURITANIA', 'Mauritania', 'MRT', '478', '222'),
       (nextval('elite_country_seq'), 'MU', 'MAURITIUS', 'Mauritius', 'MUS', '480', '230'),
       (nextval('elite_country_seq'), 'YT', 'MAYOTTE', 'Mayotte', NULL, NULL, '269'),
       (nextval('elite_country_seq'), 'MX', 'MEXICO', 'Mexico', 'MEX', '484', '52'),
       (nextval('elite_country_seq'), 'FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of',
        'FSM', '583', '691'),
       (nextval('elite_country_seq'), 'MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', '498', '373'),
       (nextval('elite_country_seq'), 'MC', 'MONACO', 'Monaco', 'MCO', '492', '377'),
       (nextval('elite_country_seq'), 'MN', 'MONGOLIA', 'Mongolia', 'MNG', '496', '976'),
       (nextval('elite_country_seq'), 'MS', 'MONTSERRAT', 'Montserrat', 'MSR', '500', '1664'),
       (nextval('elite_country_seq'), 'MA', 'MOROCCO', 'Morocco', 'MAR', '504', '212'),
       (nextval('elite_country_seq'), 'MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', '508', '258'),
       (nextval('elite_country_seq'), 'MM', 'MYANMAR', 'Myanmar', 'MMR', '104', '95'),
       (nextval('elite_country_seq'), 'NA', 'NAMIBIA', 'Namibia', 'NAM', '516', '264'),
       (nextval('elite_country_seq'), 'NR', 'NAURU', 'Nauru', 'NRU', '520', '674'),
       (nextval('elite_country_seq'), 'NP', 'NEPAL', 'Nepal', 'NPL', '524', '977'),
       (nextval('elite_country_seq'), 'NL', 'NETHERLANDS', 'Netherlands', 'NLD', '528', '31'),
       (nextval('elite_country_seq'), 'AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', '530', '599'),
       (nextval('elite_country_seq'), 'NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', '540', '687'),
       (nextval('elite_country_seq'), 'NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', '554', '64'),
       (nextval('elite_country_seq'), 'NI', 'NICARAGUA', 'Nicaragua', 'NIC', '558', '505'),
       (nextval('elite_country_seq'), 'NE', 'NIGER', 'Niger', 'NER', '562', '227'),
       (nextval('elite_country_seq'), 'NG', 'NIGERIA', 'Nigeria', 'NGA', '566', '234'),
       (nextval('elite_country_seq'), 'NU', 'NIUE', 'Niue', 'NIU', '570', '683'),
       (nextval('elite_country_seq'), 'NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', '574', '672'),
       (nextval('elite_country_seq'), 'MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', '580',
        '1670'),
       (nextval('elite_country_seq'), 'NO', 'NORWAY', 'Norway', 'NOR', '578', '47'),
       (nextval('elite_country_seq'), 'OM', 'OMAN', 'Oman', 'OMN', '512', '968'),
       (nextval('elite_country_seq'), 'PK', 'PAKISTAN', 'Pakistan', 'PAK', '586', '92'),
       (nextval('elite_country_seq'), 'PW', 'PALAU', 'Palau', 'PLW', '585', '680'),
       (nextval('elite_country_seq'), 'PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL,
        NULL, '970'),
       (nextval('elite_country_seq'), 'PA', 'PANAMA', 'Panama', 'PAN', '591', '507'),
       (nextval('elite_country_seq'), 'PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', '598', '675'),
       (nextval('elite_country_seq'), 'PY', 'PARAGUAY', 'Paraguay', 'PRY', '600', '595'),
       (nextval('elite_country_seq'), 'PE', 'PERU', 'Peru', 'PER', '604', '51'),
       (nextval('elite_country_seq'), 'PH', 'PHILIPPINES', 'Philippines', 'PHL', '608', '63'),
       (nextval('elite_country_seq'), 'PN', 'PITCAIRN', 'Pitcairn', 'PCN', '612', '0'),
       (nextval('elite_country_seq'), 'PL', 'POLAND', 'Poland', 'POL', '616', '48'),
       (nextval('elite_country_seq'), 'PT', 'PORTUGAL', 'Portugal', 'PRT', '620', '351'),
       (nextval('elite_country_seq'), 'PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', '630', '1787'),
       (nextval('elite_country_seq'), 'QA', 'QATAR', 'Qatar', 'QAT', '634', '974'),
       (nextval('elite_country_seq'), 'RE', 'REUNION', 'Reunion', 'REU', '638', '262'),
       (nextval('elite_country_seq'), 'RO', 'ROMANIA', 'Romania', 'ROM', '642', '40'),
       (nextval('elite_country_seq'), 'RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', '643', '70'),
       (nextval('elite_country_seq'), 'RW', 'RWANDA', 'Rwanda', 'RWA', '646', '250'),
       (nextval('elite_country_seq'), 'SH', 'SAINT HELENA', 'Saint Helena', 'SHN', '654', '290'),
       (nextval('elite_country_seq'), 'KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', '659', '1869'),
       (nextval('elite_country_seq'), 'LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', '662', '1758'),
       (nextval('elite_country_seq'), 'PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', '666',
        '508'),
       (nextval('elite_country_seq'), 'VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines',
        'VCT', '670', '1784'),
       (nextval('elite_country_seq'), 'WS', 'SAMOA', 'Samoa', 'WSM', '882', '684'),
       (nextval('elite_country_seq'), 'SM', 'SAN MARINO', 'San Marino', 'SMR', '674', '378'),
       (nextval('elite_country_seq'), 'ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', '678', '239'),
       (nextval('elite_country_seq'), 'SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', '682', '966'),
       (nextval('elite_country_seq'), 'SN', 'SENEGAL', 'Senegal', 'SEN', '686', '221'),
       (nextval('elite_country_seq'), 'CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL, '381'),
       (nextval('elite_country_seq'), 'SC', 'SEYCHELLES', 'Seychelles', 'SYC', '690', '248'),
       (nextval('elite_country_seq'), 'SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', '694', '232'),
       (nextval('elite_country_seq'), 'SG', 'SINGAPORE', 'Singapore', 'SGP', '702', '65'),
       (nextval('elite_country_seq'), 'SK', 'SLOVAKIA', 'Slovakia', 'SVK', '703', '421'),
       (nextval('elite_country_seq'), 'SI', 'SLOVENIA', 'Slovenia', 'SVN', '705', '386'),
       (nextval('elite_country_seq'), 'SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', '90', '677'),
       (nextval('elite_country_seq'), 'SO', 'SOMALIA', 'Somalia', 'SOM', '706', '252'),
       (nextval('elite_country_seq'), 'ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', '710', '27'),
       (nextval('elite_country_seq'), 'GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
        'South Georgia and the South Sandwich Islands', NULL, NULL, '0'),
       (nextval('elite_country_seq'), 'ES', 'SPAIN', 'Spain', 'ESP', '724', '34'),
       (nextval('elite_country_seq'), 'LK', 'SRI LANKA', 'Sri Lanka', 'LKA', '144', '94'),
       (nextval('elite_country_seq'), 'SD', 'SUDAN', 'Sudan', 'SDN', '736', '249'),
       (nextval('elite_country_seq'), 'SR', 'SURINAME', 'Suriname', 'SUR', '740', '597'),
       (nextval('elite_country_seq'), 'SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', '744', '47'),
       (nextval('elite_country_seq'), 'SZ', 'SWAZILAND', 'Swaziland', 'SWZ', '748', '268'),
       (nextval('elite_country_seq'), 'SE', 'SWEDEN', 'Sweden', 'SWE', '752', '46'),
       (nextval('elite_country_seq'), 'CH', 'SWITZERLAND', 'Switzerland', 'CHE', '756', '41'),
       (nextval('elite_country_seq'), 'SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', '760', '963'),
       (nextval('elite_country_seq'), 'TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', '158',
        '886'),
       (nextval('elite_country_seq'), 'TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', '762', '992'),
       (nextval('elite_country_seq'), 'TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA',
        '834', '255'),
       (nextval('elite_country_seq'), 'TH', 'THAILAND', 'Thailand', 'THA', '764', '66'),
       (nextval('elite_country_seq'), 'TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, '670'),
       (nextval('elite_country_seq'), 'TG', 'TOGO', 'Togo', 'TGO', '768', '228'),
       (nextval('elite_country_seq'), 'TK', 'TOKELAU', 'Tokelau', 'TKL', '772', '690'),
       (nextval('elite_country_seq'), 'TO', 'TONGA', 'Tonga', 'TON', '776', '676'),
       (nextval('elite_country_seq'), 'TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', '780', '1868'),
       (nextval('elite_country_seq'), 'TN', 'TUNISIA', 'Tunisia', 'TUN', '788', '216'),
       (nextval('elite_country_seq'), 'TR', 'TURKEY', 'Turkey', 'TUR', '792', '90'),
       (nextval('elite_country_seq'), 'TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', '795', '7370'),
       (nextval('elite_country_seq'), 'TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', '796',
        '1649'),
       (nextval('elite_country_seq'), 'TV', 'TUVALU', 'Tuvalu', 'TUV', '798', '688'),
       (nextval('elite_country_seq'), 'UG', 'UGANDA', 'Uganda', 'UGA', '800', '256'),
       (nextval('elite_country_seq'), 'UA', 'UKRAINE', 'Ukraine', 'UKR', '804', '380'),
       (nextval('elite_country_seq'), 'AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', '784', '971'),
       (nextval('elite_country_seq'), 'GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', '826', '44'),
       (nextval('elite_country_seq'), 'US', 'UNITED STATES', 'United States', 'USA', '840', '1'),
       (nextval('elite_country_seq'), 'UM', 'UNITED STATES MINOR OUTLYING ISLANDS',
        'United States Minor Outlying Islands', NULL, NULL, '1'),
       (nextval('elite_country_seq'), 'UY', 'URUGUAY', 'Uruguay', 'URY', '858', '598'),
       (nextval('elite_country_seq'), 'UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', '860', '998'),
       (nextval('elite_country_seq'), 'VU', 'VANUATU', 'Vanuatu', 'VUT', '548', '678'),
       (nextval('elite_country_seq'), 'VE', 'VENEZUELA', 'Venezuela', 'VEN', '862', '58'),
       (nextval('elite_country_seq'), 'VN', 'VIET NAM', 'Viet Nam', 'VNM', '704', '84'),
       (nextval('elite_country_seq'), 'VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', '92',
        '1284'),
       (nextval('elite_country_seq'), 'VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', '850', '1340'),
       (nextval('elite_country_seq'), 'WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', '876', '681'),
       (nextval('elite_country_seq'), 'EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', '732', '212'),
       (nextval('elite_country_seq'), 'YE', 'YEMEN', 'Yemen', 'YEM', '887', '967'),
       (nextval('elite_country_seq'), 'ZM', 'ZAMBIA', 'Zambia', 'ZMB', '894', '260'),
       (nextval('elite_country_seq'), 'ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', '716', '263');