server:
  port: 8080
  servlet:
    context-path: /elite

spring:
  banner:
    location: classpath:banner.txt
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/elite
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  sql:
    init:
      platform: postgres

springdoc:
  api-docs:
    path: /swagger/api-definition
  swagger-ui:
    path: /swagger.html
