name: deploy
on:
  push:
    branches:
      - master

jobs:
 build:
 steps:
 - checkout
 - run: mvn clean package
 - run: echo "BUILD SUCCESS"
test:
 steps:
 - checkout
 - run: mvn test
 - run: echo "TEST SUCCESS"